# Generated by Django 4.2.1 on 2023-06-03 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=200)),
                ('h1', models.CharField(blank=True, max_length=200)),
                ('f1', models.CharField(blank=True, max_length=200)),
                ('h2', models.CharField(blank=True, max_length=200)),
                ('f2', models.CharField(blank=True, max_length=200)),
                ('h3', models.CharField(blank=True, max_length=200)),
                ('f3', models.CharField(blank=True, max_length=200)),
                ('h4', models.CharField(blank=True, max_length=200)),
                ('f4', models.CharField(blank=True, max_length=200)),
                ('h5', models.CharField(blank=True, max_length=200)),
                ('f5', models.CharField(blank=True, max_length=200)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
    ]
