# Generated by Django 4.2.1 on 2023-06-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_myre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myre',
            name='quest',
        ),
        migrations.AlterField(
            model_name='myre',
            name='q1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
