# Generated by Django 4.2.1 on 2023-06-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_myre_quest_alter_myre_q1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myre',
            name='q1',
            field=models.IntegerField(blank=True, max_length=200),
        ),
    ]
